print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/anthonyromrell/Documents/GitRepos/2670Scripting/StarCatcher/Assets/MovingBox.ma"`)
{		
	file -o "/Users/anthonyromrell/Documents/GitRepos/2670Scripting/StarCatcher/Assets/MovingBox.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/anthonyromrell/Documents/GitRepos/2670Scripting/StarCatcher/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/anthonyromrell/Documents/GitRepos/2670Scripting/StarCatcher/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/anthonyromrell/Documents/GitRepos/2670Scripting/StarCatcher/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
